# Use Node.js 18
FROM node:18.19.0

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Set up the working directory
WORKDIR /front-angular

# Copy project files into the container
COPY . .

# Install dependencies
RUN npm install

# Command to serve the Angular app
CMD ng serve --host 0.0.0.0 --port 4200

# Expose the Angular development server port
EXPOSE 4200
